# Generated by Django 6.0.6 on 2026-06-23 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="quizzes.question",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="quizzes.test",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizzes.test",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="quizzes.subject",
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="quizzes.answer",
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="quizzes.attempt",
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="quizzes.question",
            ),
        ),
    ]
