# Generated by Django 6.0.6 on 2026-07-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_alter_answer_question_alter_attempt_test_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attempt",
            name="score",
        ),
        migrations.AddField(
            model_name="attempt",
            name="total_questions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
